# Generated by Django 4.2.2 on 2023-06-12 00:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='', max_length=50, verbose_name='图标')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('pct', models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)], verbose_name='完成度')),
                ('ord', models.IntegerField(default=0, verbose_name='排序号')),
                ('in_actions', models.BooleanField(default=False, verbose_name='动作列表')),
            ],
            options={
                'verbose_name': '🔖 状态',
                'verbose_name_plural': '🔖 状态',
                'ordering': ['ord'],
            },
        ),
        migrations.CreateModel(
            name='CatalogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('ord', models.IntegerField(default=0, verbose_name='排序')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'verbose_name': '📝 工作区',
                'verbose_name_plural': '📝 工作区',
            },
        ),
        migrations.CreateModel(
            name='ArchivedTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
                ('icon', models.CharField(choices=[('📦', '📦'), ('💼', '💼'), ('📒', '📒'), ('📌', '📌'), ('🎁', '🎁'), ('💻', '💻'), ('🎈', '🎈'), ('🔖', '🔖'), ('🗳', '🗳'), ('🔔', '🔔'), ('🪛', '🪛'), ('🚀', '🚀')], default='📦', max_length=50, verbose_name='图标')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('weight', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='权重')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('finish_time', models.DateField(blank=True, null=True, verbose_name='完成时间')),
                ('archived', models.BooleanField(default=False, verbose_name='归档')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='taskmgr.archivedtaskmodel')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskmgr.statemodel', verbose_name='状态')),
            ],
            options={
                'verbose_name': '🗜 已归档',
                'verbose_name_plural': '🗜 已归档',
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
            ],
            options={
                'verbose_name': '🗃 任务',
                'verbose_name_plural': '🗃 任务',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taskmgr.archivedtaskmodel',),
        ),
        migrations.CreateModel(
            name='CatalogItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(-1)], verbose_name='包含层级')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmgr.catalogmodel', verbose_name='目录')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmgr.taskmodel', verbose_name='任务')),
            ],
            options={
                'verbose_name': '目录项',
                'verbose_name_plural': '目录项',
            },
        ),
    ]
